### PR TITLE
Closes #555: Add pipeline retries

### LINKED ISSUE #555: Retry if sample fails due to spot instance termination

### PR DESCRIPTION
**Pull request by cdebourcy**
Already a large fraction of the newly submitted samples failed just because of spot instance termination.
Also deduplicated some of the batch submission code.

### CODE REVIEW

File: app/models/pipeline_run_stage.rb [hunk 1]
```diff
@@ -93,6 +106,7 @@ def update_job_status
       if job_hash['container'] && job_hash['container']['logStreamName']
         self.job_log_id = job_hash['container']['logStreamName']
       end
+      run_job if instance_terminated?(job_hash) # retry if necessary
```
Comment (yunfangjuan) [inline app/models/pipeline_run_stage.rb]: if instance_terminated?(job_hash)
run_job
return
end 

so you don't save twice

Comment (cdebourcy) [reply app/models/pipeline_run_stage.rb]: Ok! Thanks
