### PR TITLE
Closes #1210: fix "delete project" button

### LINKED ISSUE #1210: "Delete project" button should not show up when sample list is only empty due to filters
screen shot 2018-04-23 at 3 32 15 pm

### PR DESCRIPTION
**Pull request by cdebourcy**

### CODE REVIEW

File: app/assets/src/components/Samples.jsx [hunk 1]
```diff
@@ -1891,7 +1893,10 @@ function ProjectInfoHeading({
         {state.selectedProjectId ? project_menu : null}
         {table_download_dropdown}
         {compare_button}
-        {state.selectedProjectId && state.allSamples.length == 0
+        {state.selectedProjectId &&
+        canEditProject(state.selectedProjectId) &&
```
Comment (jshoe) [inline app/assets/src/components/Samples.jsx]: would this work even if you didn't pass it in? since canEditProject was already bound to 'this' at the top?

Comment (cdebourcy) [reply app/assets/src/components/Samples.jsx]: It didn't...
